version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pao_db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: Deus1010 # troque por senha forte
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U appuser"]
      interval: 10s
      retries: 5
      start_period: 20s
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
  # Use externally provided DATABASE_URL (configure in Coolify UI or .env file)
  DATABASE_URL: ${DATABASE_URL}
  PORT: 3001
    ports:
      - "3001:3001"
volumes:
  pgdata:
